version: "3.9"

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: http://localhost:8080/api
    container_name: mini-shop-frontend
    ports:
      - "3000:80"
    restart: always